// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFxjEdOBPwoULiv6jo9YQE8_UvOZ8tj6E',
    appId: '1:909570184755:web:a0270f2e43d0715adb7546',
    messagingSenderId: '909570184755',
    projectId: 'latihanuts-b88d6',
    authDomain: 'latihanuts-b88d6.firebaseapp.com',
    databaseURL: 'https://latihanuts-b88d6-default-rtdb.firebaseio.com',
    storageBucket: 'latihanuts-b88d6.firebasestorage.app',
    measurementId: 'G-YMY4WB1D7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBodGDEz92CJF6Oxripg3Ei8bgmLFTsgMI',
    appId: '1:909570184755:android:58ea25d16f8042a7db7546',
    messagingSenderId: '909570184755',
    projectId: 'latihanuts-b88d6',
    databaseURL: 'https://latihanuts-b88d6-default-rtdb.firebaseio.com',
    storageBucket: 'latihanuts-b88d6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFxjEdOBPwoULiv6jo9YQE8_UvOZ8tj6E',
    appId: '1:909570184755:web:0ee68754bf51c580db7546',
    messagingSenderId: '909570184755',
    projectId: 'latihanuts-b88d6',
    authDomain: 'latihanuts-b88d6.firebaseapp.com',
    databaseURL: 'https://latihanuts-b88d6-default-rtdb.firebaseio.com',
    storageBucket: 'latihanuts-b88d6.firebasestorage.app',
    measurementId: 'G-TBHM8QC61H',
  );
}
